name: example
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  receipt:
    path: ../
  flipper_models: ^0.0.1-dev.5
  realm: ^3.2.0

dependency_overrides:
  http: ^1.2.1
  meta: ^1.12.0
  intl: ^0.19.0
  
  # realm_dart: 2.1.0
  # realm_generator: 2.1.0
  # realm_common: 2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - google_fonts/
