name: receipt
description: A new receipt package for print
version: 1.0.0-dev.2
repository: "https://github.com/yegobox/receipt"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  printing: ^5.7.5
  pdf: ^3.7.3
  open_file: ^3.2.1
  gap: ^2.0.0
  flipper_models: ^0.0.1-dev.7
  isar: ^2.4.0
  isar_flutter_libs: ^2.4.0
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7
  isar_generator: ^2.4.0

flutter:
