name: receipt
description: A new receipt package for print
version: 1.0.0-dev.2
repository: "https://github.com/yegobox/receipt"


environment:
  sdk: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter
  # printing: 5.10.4
  printing:
    git:
      url: https://github.com/DavBfr/dart_pdf
      ref: master
      path: printing
  pdf: ^3.10.3
  open_filex: ^4.1.1
  gap: ^2.0.0
  flipper_models: ^0.0.1-dev.7
  isar: ^4.0.0-dev.13
  isar_flutter_libs: ^4.0.0-dev.13
  qr_flutter: ^4.0.0
  flipper_services: ^1.0.0
  universal_platform: ^1.0.0+1
  lecle_downloads_path_provider: ^0.0.2+7
  get_storage: ^2.0.3
  path_provider: ^2.0.15
  path: ^1.8.1
  permission_handler: ^10.4.3
dependency_overrides:
  http: ^1.1.0
dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - ../../assets/
