name: receipt
description: A new receipt package for print
version: 1.0.0-dev.2
repository: "https://github.com/yegobox/receipt"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  printing: ^5.13.3
  pdf: ^3.10.3
  open_filex: ^4.5.0
  gap: ^2.0.0
  flipper_models: ^0.0.1-dev.5

  qr_flutter: ^4.0.0
  flipper_services: ^1.0.0-dev
  universal_platform: ^1.0.0+1
  path_provider: ^2.1.4
  path: ^1.8.1
  permission_handler: ^11.3.1
  image: ^4.0.17
  intl: ^0.19.0
  dotted_line: ^3.2.2
  # syncfusion_flutter_pdf: ^26.2.11
  # syncfusion_flutter_barcodes: ^26.2.11
  
dependency_overrides:
  http: ^1.2.2
  meta: ^1.12.0
  web: ^0.5.1
dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
